### ISSUE TITLE
 'curl_setopt' error

### ISSUE THREAD

**Issue by wpannone** [rlaphoenix/DIRECTIPTV#1]
When using on a Windows 10 environment, tried with both XAMPP and Wamp, I keep getting the following error when attempting to launch the .php in Firefox:

`Parse error: syntax error, unexpected 'curl_setopt' (T_STRING) in C:\wamp64\www\DIRECTIPTV.php on line 20 `

Necessary prerequisite cookies were grabbed and added to the .php as such:

`$cookies = 'JSESSIONID=xxxxxxxxxxxxxxxxxxxxxx; DYN_USER_ID=xxxxxxxxx; DYN_USER_CONFIRM=xxxxxxxxxxxxxxxxxxxxxxxxxxx;'`

**Comment by rlaphoenix** [comment]
Your issue seems to be related to a missing ending `;` at the end of the line after the `'`.
